-- ============================================================
-- מיגרציה: טבלת prospects — מפרסמים פוטנציאליים שחולצו מקובצי PDF
-- ------------------------------------------------------------
-- הכלי (js/prospects.js + Edge Function בשם extract-advertisers) סורק
-- עיתונים מתחרים / מגזינים / גיליונות קודמים שלנו, מזהה כל מודעה,
-- ושומר כאן את המפרסמים שרלוונטי להציע להם פרסום — בנפרד מהלידים.
-- "העבר ללידים" יוצר ליד רגיל ומסמן כאן status='converted' + lead_id.
-- צילומי המודעות נשמרים בבאקט הקיים ad-files תחת prospects/ (אין צורך
-- בבאקט חדש או בשינוי מדיניות אחסון).
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ==================== 1. הטבלה ====================
create table if not exists public.prospects (
  id            bigint generated by default as identity primary key,
  name          text not null,
  name_key      text,                       -- שם מנורמל להשוואה
  phone         text,
  phone_key     text,                       -- 9 ספרות אחרונות להשוואה
  phone2        text,
  email         text,
  website       text,
  field         text,                       -- תחום העסק
  location      text,                       -- יישוב / כתובת
  service_area  text,                       -- אזור שירות כפי שמופיע במודעה
  is_online     boolean not null default false,
  region_fit    text,                       -- local | serves_area | online_national | far
  best_size     text,                       -- הגודל הגדול ביותר שנראה
  size_rank     int not null default 0,
  appearances   int not null default 1,     -- כמה פעמים נמצא (בכל הסריקות)
  sources       jsonb not null default '[]'::jsonb,  -- [{kind,pub,date,page,size,file,at}]
  image_path    text,                       -- צילום המודעה (ad-files/prospects/...)
  summary       text,                       -- תיאור קצר של המודעה
  status        text not null default 'new',
  filter_reason text,                       -- למה סונן (כש-status='filtered')
  winback       boolean not null default false, -- לקוח בעבר — להחזיר
  customer_id   bigint,                     -- כשזה לקוח עבר
  lead_id       bigint,                     -- אחרי "העבר ללידים"
  created_by    uuid,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'prospects_status_check') then
    alter table public.prospects add constraint prospects_status_check
      check (status in ('new','converted','rejected','filtered'));
  end if;
end $mig$;

create index if not exists prospects_status_idx    on public.prospects (status);
create index if not exists prospects_phone_key_idx on public.prospects (phone_key);
create index if not exists prospects_name_key_idx  on public.prospects (name_key);

comment on table public.prospects is 'מפרסמים פוטנציאליים שחולצו מקובצי PDF (מסך "מפרסמים פוטנציאליים")';

-- ==================== 2. RLS — מנהל בלבד ====================
alter table public.prospects enable row level security;

do $mig$
begin
  execute 'drop policy if exists prospects_admin on public.prospects';
  execute $p$
    create policy prospects_admin on public.prospects
      for all to authenticated
      using (exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role = 'admin'))
      with check (exists (select 1 from public.profiles p
                          where p.id = auth.uid() and p.active and p.role = 'admin'))
  $p$;
end $mig$;

-- ==================== 3. הגדרות סינון (נערכות במסך עצמו) ====================
-- prospect_region: האזור שהעיתון משרת (ריק → נלקח paper_city / שם העיתון)
-- prospect_content_rules: אילו מודעות לא מתאימות לאופי העיתון
insert into public.settings (key, value) values ('prospect_region', '')
  on conflict (key) do nothing;
insert into public.settings (key, value) values ('prospect_content_rules', '')
  on conflict (key) do nothing;
