-- ============================================================
-- מיגרציה: צ'אט צוות פנימי (שלב 1)
-- ------------------------------------------------------------
-- 1. team_messages — הודעות הצ'אט. ערוץ אחד קבוצתי ('group')
--    וערוץ אישי לכל סוכן מול המנהל ('dm:<agent_id>').
-- 2. team_message_reads — "עד מתי קראתי" לכל משתמש בכל ערוץ
--    (שורה אחת לערוץ למשתמש — זול בהרבה מ-jsonb על כל הודעה).
-- RLS: מנהל קורא וכותב בכל הערוצים; משתמש מכירות רק בערוץ
-- הקבוצתי ובערוץ האישי של הסוכן המקושר אליו (my_agent_id()).
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ---------- 1. הודעות ----------
create table if not exists public.team_messages (
  id bigint generated by default as identity,
  channel text not null,
  sender_user uuid default auth.uid(),
  body text not null,
  created_at timestamptz not null default now()
);

-- אילוצים — בנפרד כדי שהרצה חוזרת לא תיכשל
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'team_messages_pkey') then
    alter table public.team_messages add constraint team_messages_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'team_messages_channel_check') then
    alter table public.team_messages add constraint team_messages_channel_check
      check (channel = 'group' or channel like 'dm:%');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'team_messages_body_check') then
    alter table public.team_messages add constraint team_messages_body_check
      check (length(body) between 1 and 4000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'team_messages_sender_fkey') then
    alter table public.team_messages add constraint team_messages_sender_fkey
      foreign key (sender_user) references auth.users(id) on delete set null;
  end if;
end $$;

create index if not exists team_messages_channel_idx on public.team_messages (channel, id desc);
create index if not exists team_messages_created_idx on public.team_messages (created_at desc);

comment on table public.team_messages is
  'צ''אט צוות פנימי: ערוץ קבוצתי (group) וערוצים אישיים מנהל-סוכן (dm:<agent_id>)';

-- ---------- 2. סימוני קריאה ----------
create table if not exists public.team_message_reads (
  channel text not null,
  user_id uuid not null default auth.uid(),
  last_read_at timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'team_message_reads_pkey') then
    alter table public.team_message_reads add constraint team_message_reads_pkey
      primary key (channel, user_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'team_message_reads_user_fkey') then
    alter table public.team_message_reads add constraint team_message_reads_user_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;
end $$;

comment on table public.team_message_reads is
  'צ''אט צוות: חותמת "עד מתי קראתי" לכל משתמש בכל ערוץ — לחישוב באדג'' לא-נקראו';

-- ---------- 3. RLS ----------
-- הרשאת ערוץ (כמו בשאר הטבלאות — my_role/my_agent_id/emu_is_admin מהסכימה):
-- מנהל: הכל. מכירות: הערוץ הקבוצתי + הערוץ האישי של הסוכן שלו בלבד.
alter table public.team_messages enable row level security;

drop policy if exists team_messages_select on public.team_messages;
create policy team_messages_select on public.team_messages
  for select to authenticated
  using (
    public.emu_is_admin()
    or ( public.my_role() = 'sales'
         and (channel = 'group' or channel = 'dm:' || public.my_agent_id()::text) )
  );

drop policy if exists team_messages_insert on public.team_messages;
create policy team_messages_insert on public.team_messages
  for insert to authenticated
  with check (
    sender_user = auth.uid()
    and (
      public.emu_is_admin()
      or ( public.my_role() = 'sales'
           and (channel = 'group' or channel = 'dm:' || public.my_agent_id()::text) )
    )
  );
-- אין update/delete בשלב 1 — הודעה שנשלחה נשארת כפי שהיא.

alter table public.team_message_reads enable row level security;

drop policy if exists team_message_reads_own on public.team_message_reads;
create policy team_message_reads_own on public.team_message_reads
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant all on public.team_messages to anon, authenticated, service_role;
grant all on public.team_message_reads to anon, authenticated, service_role;
