-- ============================================================
-- מיגרציה: צ'אטבוט הפקת חשבוניות ממלל חופשי (iCount)
-- ------------------------------------------------------------
-- 1. טבלת לוג invoice_requests — כל בקשת הפקה מהצ'אט נרשמת בה:
--    המלל הגולמי, הפענוח, השדות הסופיים, ותוצאת ההפקה מ-iCount.
-- 2. מפתחות ברירת מחדל בהגדרות: המתג כבוי ('0') ומע"מ 18%.
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

create table if not exists public.invoice_requests (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  user_id uuid,
  raw_text text not null,
  parsed_json jsonb,
  final_fields jsonb,
  icount_doc_number text,
  icount_doc_url text,
  status text not null default 'draft',
  error_message text
);

-- אילוצים — בנפרד כדי שהרצה חוזרת לא תיכשל
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'invoice_requests_pkey') then
    alter table public.invoice_requests add constraint invoice_requests_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'invoice_requests_status_check') then
    alter table public.invoice_requests add constraint invoice_requests_status_check
      check (status in ('draft','issued','cancelled','error'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'invoice_requests_user_id_fkey') then
    alter table public.invoice_requests add constraint invoice_requests_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete set null;
  end if;
end $$;

create index if not exists invoice_requests_created_idx on public.invoice_requests (created_at desc);
create index if not exists invoice_requests_status_idx  on public.invoice_requests (status);

comment on table public.invoice_requests is
  'לוג צ''אט הפקת החשבוניות: מלל חופשי → פענוח → אישור → הפקה ב-iCount';

-- RLS: מנהל ומכירות בלבד (כמו שאר מסכי הכספים)
alter table public.invoice_requests enable row level security;

drop policy if exists invoice_requests_select on public.invoice_requests;
create policy invoice_requests_select on public.invoice_requests
  for select to authenticated
  using (exists (select 1 from public.profiles p
                 where p.id = auth.uid() and p.active and p.role in ('admin','sales')));

drop policy if exists invoice_requests_insert on public.invoice_requests;
create policy invoice_requests_insert on public.invoice_requests
  for insert to authenticated
  with check (exists (select 1 from public.profiles p
                      where p.id = auth.uid() and p.active and p.role in ('admin','sales')));

drop policy if exists invoice_requests_update on public.invoice_requests;
create policy invoice_requests_update on public.invoice_requests
  for update to authenticated
  using (exists (select 1 from public.profiles p
                 where p.id = auth.uid() and p.active and p.role in ('admin','sales')))
  with check (exists (select 1 from public.profiles p
                      where p.id = auth.uid() and p.active and p.role in ('admin','sales')));

grant all on public.invoice_requests to anon, authenticated, service_role;

-- הגדרות ברירת מחדל: המתג כבוי עד שמדליקים אותו במסך ההגדרות,
-- ושיעור המע"מ (באחוזים) — לא מקודד קשיח בקוד.
insert into public.settings (key, value) values ('invoice_chat_enabled', '0')
  on conflict (key) do nothing;
insert into public.settings (key, value) values ('vat_rate', '18')
  on conflict (key) do nothing;
