-- ============================================================
-- מיגרציה: בוט הזנת נתונים (צ'אט תפעולי לסוכנים) — MVP עסקה
-- ------------------------------------------------------------
-- 1. טבלת לוג entry_requests — כל הזנה מהבוט נרשמת בה:
--    המלל הגולמי, הפענוח, השדות הסופיים והתוצאה (חוזה/מודעות).
--    הבוט תפעולי בלבד — לעולם לא מפיק מסמך כספי.
-- 2. מתג בהגדרות: data_entry_bot_enabled ('0' כברירת מחדל).
--    הבוט יכול לפעול גם במופע בלי EZcount — בניגוד לצ'אט החשבוניות.
-- 3. כלל התראה agent_deal_closed במנוע ההתראות הקיים:
--    "הסוכן X סגר עסקה" — נמען: מנהל (RLS של alerts נשאר מנהל בלבד).
-- דורש שמיגרציות מנוע ההתראות (2026-08-24 + 2026-08-30_v2) כבר רצו.
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- עד שהמיגרציה רצה — הפיצ'ר רדום (המתג לא קיים = כבוי).
-- ============================================================

-- ==================== 1. טבלת הלוג ====================
create table if not exists public.entry_requests (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  user_id uuid,
  raw_text text not null,
  parsed_json jsonb,
  final_fields jsonb,
  result_json jsonb,
  status text not null default 'draft',
  error_message text
);

-- אילוצים — בנפרד כדי שהרצה חוזרת לא תיכשל
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'entry_requests_pkey') then
    alter table public.entry_requests add constraint entry_requests_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'entry_requests_status_check') then
    alter table public.entry_requests add constraint entry_requests_status_check
      check (status in ('draft','committed','cancelled','error'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'entry_requests_user_id_fkey') then
    alter table public.entry_requests add constraint entry_requests_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete set null;
  end if;
end $$;

create index if not exists entry_requests_created_idx on public.entry_requests (created_at desc);
create index if not exists entry_requests_status_idx  on public.entry_requests (status);

comment on table public.entry_requests is
  'לוג בוט הזנת הנתונים: מלל חופשי → פענוח → אישור → כתיבת חוזה+מודעות (ללא מסמך כספי)';

-- RLS: מנהל רואה הכל; סוכן (sales) רואה ומעדכן רק את ההזנות של עצמו
alter table public.entry_requests enable row level security;

drop policy if exists entry_requests_select on public.entry_requests;
create policy entry_requests_select on public.entry_requests
  for select to authenticated
  using (exists (select 1 from public.profiles p
                 where p.id = auth.uid() and p.active
                   and (p.role = 'admin' or (p.role = 'sales' and user_id = auth.uid()))));

drop policy if exists entry_requests_insert on public.entry_requests;
create policy entry_requests_insert on public.entry_requests
  for insert to authenticated
  with check (user_id = auth.uid()
    and exists (select 1 from public.profiles p
                where p.id = auth.uid() and p.active and p.role in ('admin','sales')));

drop policy if exists entry_requests_update on public.entry_requests;
create policy entry_requests_update on public.entry_requests
  for update to authenticated
  using (exists (select 1 from public.profiles p
                 where p.id = auth.uid() and p.active
                   and (p.role = 'admin' or (p.role = 'sales' and user_id = auth.uid()))))
  with check (exists (select 1 from public.profiles p
                      where p.id = auth.uid() and p.active
                        and (p.role = 'admin' or (p.role = 'sales' and user_id = auth.uid()))));

grant all on public.entry_requests to anon, authenticated, service_role;

-- ==================== 2. מתג בהגדרות ====================
insert into public.settings (key, value) values ('data_entry_bot_enabled', '0')
  on conflict (key) do nothing;

-- ==================== 3. כלל התראה למנהל ====================
-- agent_deal_closed מפורסם מהבוט דרך alerts_publish_event אחרי הקמת עסקה.
-- ה-payload נושא id ייחודי פר הזנה (dedup), ובכוונה בלי מפתח customer_id
-- ברמה העליונה — כדי ששתי עסקאות לאותו לקוח לא ייבלמו זו על זו במנוע.
-- הכלל פעיל, אך המנוע כולו כפוף למתג הראשי alerts_enabled.
insert into public.alert_rules (event_type, enabled, condition, channels, template, throttle_hours, recipients)
select 'agent_deal_closed', true, '{}'::jsonb, array['inapp'],
       '🤝 הסוכן {agent_name} סגר עסקה עם {customer_name} — {scope} בסך {amount}',
       24, '{"roles":["admin"]}'::jsonb
where not exists (select 1 from public.alert_rules where event_type = 'agent_deal_closed');
