-- ============================================================
-- מיגרציה: סוכנויות פרסום ועמלות (פיצ'ר #7) — תשתית
-- ------------------------------------------------------------
-- טבלת agencies + שיוך לקוח לסוכנות (customers.agency_id).
-- הסוכנות מגדירה אחוז עמלה להחזר ועל שם מי מונפקת החשבונית
-- כברירת מחדל (לקוח / סוכנות). חישוב העמלה הוא תצוגה בלבד —
-- שום תשלום עמלה לא מבוצע אוטומטית.
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ==================== 1. טבלת הסוכנויות ====================
create table if not exists public.agencies (
  id             bigint generated by default as identity,
  name           text not null,
  invoice_name   text,
  business_id    text,
  contact_person text,
  phone          text,
  email          text,
  commission_pct numeric not null default 0,
  invoice_target text not null default 'customer',
  notes          text,
  created_at     timestamptz not null default now()
);

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'agencies_pkey') then
    alter table public.agencies add constraint agencies_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'agencies_invoice_target_check') then
    alter table public.agencies add constraint agencies_invoice_target_check
      check (invoice_target in ('customer','agency'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'agencies_commission_pct_check') then
    alter table public.agencies add constraint agencies_commission_pct_check
      check (commission_pct >= 0 and commission_pct <= 100);
  end if;
end $mig$;

comment on table public.agencies is 'סוכנויות פרסום: אחוז עמלה להחזר + על שם מי מונפקת החשבונית';

-- ==================== 2. שיוך לקוח לסוכנות ====================
alter table public.customers
  add column if not exists agency_id bigint;

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'customers_agency_id_fkey') then
    alter table public.customers add constraint customers_agency_id_fkey
      foreign key (agency_id) references public.agencies(id) on delete set null;
  end if;
end $mig$;

create index if not exists customers_agency_idx on public.customers (agency_id) where agency_id is not null;

-- ==================== 3. RLS ====================
-- מנהל: הכל. מכירות: קריאה (רואים לאיזו סוכנות לקוח שייך).
alter table public.agencies enable row level security;

do $mig$
begin
  execute 'drop policy if exists agencies_admin_all on public.agencies';
  execute $p$
    create policy agencies_admin_all on public.agencies
      for all to authenticated
      using (exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role = 'admin'))
      with check (exists (select 1 from public.profiles p
                          where p.id = auth.uid() and p.active and p.role = 'admin'))
  $p$;
  execute 'drop policy if exists agencies_sales_read on public.agencies';
  execute $p$
    create policy agencies_sales_read on public.agencies
      for select to authenticated
      using (exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role in ('sales','editor','graphics')))
  $p$;
end $mig$;

grant all on public.agencies to anon, authenticated, service_role;
