-- ============================================================
-- מיגרציה: מודול רווחיות, שכר ועמלות (05.10.2026)
-- ------------------------------------------------------------
-- שכבת תגמול עובדים מעל הנתונים הקיימים (ads / contracts / issues /
-- ad_files / expenses). הקוד: js/payroll-engine.js (חישוב טהור) +
-- js/payroll.js (מסכים).
--
-- טבלאות חדשות:
--   agent_comp            — תגמול פר סוכן: שכר בסיס (NULL = עמלה בלבד),
--                           יעד חודשי, % עמלה עד היעד / מעל היעד,
--                           tiers (jsonb, אופציונלי — מדרגות נוספות בעתיד).
--   agent_manager_cut     — נתח מנהלת מוקד: מנהלת, הנציגות שתחתיה, אחוז.
--   revenue_recognition   — הכרה בהכנסה בסגירת חודש: עסקה (חוזה) × חודש,
--                           סכום מוכר, נכלל/לא נכלל. ייחודי (contract_id, month)
--                           — סגירה חוזרת של אותו חודש מעדכנת ולא משכפלת.
--   revenue_month_close   — חודשים שנסגרו (מי ומתי).
--   payroll_bonus         — בונוס ידני פר עובד × חודש (מסך השכר).
--   staff_hourly_rate     — שכר שעתי לעובד/ת (הגרפיקאית) — עלות הגרפיקה בחודש =
--                           שעות שעון הנוכחות × השכר השעתי. מנהל בלבד.
--   revenue_month_close.graphics_cost_per_ad — עלות גרפיקה למודעה שנשמרה
--                           בסגירת החודש (כדי שהסוכן יראה את עלות המודעות שלו
--                           בלי לראות שעות ושכר של הגרפיקאית).
--
-- עמודה חדשה ב-ads:
--   design_fee_net — חיוב עיצוב (נטו) שסומן ידנית בכרטיס המודעה בכפתור
--                    "🎨 עיצוב ₪50 + מע"מ" (לא אוטומטי — תיקון קל לא מחויב).
--                    הלחיצה יוצרת גם חיוב פתוח ללקוח (charges, מסומן #design:<id>).
--                    NULL = לא עוצבה אצלנו. נשמר התעריף שבתוקף בזמן הסימון.
--
-- הגדרות (settings) — נזרעות רק אם חסרות:
--   profitability_enabled = '0'   (המודול כבוי עד הדלקה ידנית בהגדרות)
--   graphics_fee_net      = '50'  (חיוב העיצוב ללקוח, נטו — ערך הכפתור)
-- הגדרה אופציונלית: graphics_cost_net — עלות הגרפיקה לעסק למודעה מעוצבת
--                   (נטו; ריק = כגובה החיוב ללקוח).
-- הגדרה אופציונלית (נקבעת במסך ההגדרות, לא נזרעת):
--   default_agent_id      — הסוכן שמודעה בלי סוכן (ובלי סוכן ללקוח) נזקפת לו.
--                           ריק = הסוכן המקושר למשתמש מנהל.
--
-- הרשאות (RLS):
--   מנהל — הכל. סוכן (sales) — רק את השורות של עצמו ב-agent_comp
--   וב-revenue_recognition (קריאה בלבד). agent_manager_cut, payroll_bonus ו-
--   staff_hourly_rate — מנהל בלבד. אף משתמש שאינו מנהל לא כותב לשום טבלה כאן.
--   המדיניות עצמאית (בודקת profiles/agents ישירות) — לא תלויה ב-emu_is_admin.
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ==================== 0. עלות עיצוב למודעה ====================
alter table public.ads add column if not exists design_fee_net numeric(10,2);
comment on column public.ads.design_fee_net is 'חיוב עיצוב נטו שסומן ידנית בכפתור בכרטיס המודעה (NULL = לא עוצבה אצלנו)';

-- ==================== 1. טבלאות ====================
create table if not exists public.agent_comp (
  agent_id             bigint primary key references public.agents(id) on delete cascade,
  base_salary          numeric(12,2),            -- NULL = עמלה בלבד
  monthly_target       numeric(12,2),            -- ₪ נטו; NULL/0 = בלי מדרגה עליונה
  commission_pct_base  numeric(6,3) not null default 0,  -- % על ההכנסה עד היעד
  commission_pct_above numeric(6,3),             -- % על החלק שמעל היעד (NULL = כמו הבסיס)
  tiers                jsonb,                    -- [{ "from": 0, "pct": 5 }, { "from": 20000, "pct": 8 }, ...] — גובר על שני השדות אם מוגדר
  active               boolean not null default true,
  updated_by           uuid,
  updated_at           timestamptz not null default now()
);
comment on table public.agent_comp is 'תגמול עובד: בסיס + עמלה מדורגת לפי יעד חודשי (מודול רווחיות ושכר)';

create table if not exists public.agent_manager_cut (
  id               bigint generated by default as identity primary key,
  manager_agent_id bigint not null references public.agents(id) on delete cascade,
  source_agent_ids bigint[] not null default '{}',
  pct              numeric(6,3) not null default 0,
  active           boolean not null default true,
  updated_by       uuid,
  updated_at       timestamptz not null default now()
);
create unique index if not exists agent_manager_cut_mgr_uq on public.agent_manager_cut (manager_agent_id);
comment on table public.agent_manager_cut is 'נתח מנהלת מוקד: % מההכנסה המוכרת של הנציגות שתחתיה — תוספת, לא מנוכה מהן';

create table if not exists public.revenue_recognition (
  id                bigint generated by default as identity primary key,
  contract_id       bigint not null references public.contracts(id) on delete cascade,
  agent_id          bigint references public.agents(id) on delete set null,
  month             text not null check (month ~ '^[0-9]{4}-[0-9]{2}$'),
  amount_recognized numeric(12,2) not null default 0,  -- נטו, לפני מע"מ
  included          boolean not null default false,
  confirmed_by      uuid,
  confirmed_at      timestamptz not null default now()
);
create unique index if not exists revenue_recognition_ct_month_uq on public.revenue_recognition (contract_id, month);
create index if not exists revenue_recognition_month_idx on public.revenue_recognition (month, agent_id);
comment on table public.revenue_recognition is 'הכרה בהכנסה בסגירת חודש — עסקה רב-גיליונית × חודש (רק מה שחיים אישר)';

create table if not exists public.revenue_month_close (
  month      text primary key check (month ~ '^[0-9]{4}-[0-9]{2}$'),
  closed_by  uuid,
  closed_at  timestamptz not null default now()
);

alter table public.revenue_month_close add column if not exists graphics_cost_per_ad numeric(12,2);

create table if not exists public.staff_hourly_rate (
  profile_id  uuid primary key references public.profiles(id) on delete cascade,
  hourly_rate numeric(10,2) not null default 0,   -- ₪ לשעה (עלות מעביד)
  updated_by  uuid,
  updated_at  timestamptz not null default now()
);
comment on table public.staff_hourly_rate is 'שכר שעתי — עלות הגרפיקה = שעות נוכחות × שכר שעתי (מנהל בלבד)';

create table if not exists public.payroll_bonus (
  id         bigint generated by default as identity primary key,
  agent_id   bigint not null references public.agents(id) on delete cascade,
  month      text not null check (month ~ '^[0-9]{4}-[0-9]{2}$'),
  amount     numeric(12,2) not null default 0,
  note       text,
  updated_by uuid,
  updated_at timestamptz not null default now()
);
create unique index if not exists payroll_bonus_agent_month_uq on public.payroll_bonus (agent_id, month);

-- ==================== 2. RLS ====================
alter table public.agent_comp          enable row level security;
alter table public.agent_manager_cut   enable row level security;
alter table public.revenue_recognition enable row level security;
alter table public.revenue_month_close enable row level security;
alter table public.payroll_bonus       enable row level security;
alter table public.staff_hourly_rate   enable row level security;

do $mig$
declare
  v_admin text := $c$exists (select 1 from public.profiles p where p.id = auth.uid() and p.active and p.role = 'admin')$c$;
  v_sales text := $c$exists (select 1 from public.profiles p where p.id = auth.uid() and p.active and p.role = 'sales')$c$;
  v_mine  text := $c$agent_id in (select a.id from public.agents a where a.profile_id = auth.uid())$c$;
  t text;
begin
  -- מנהל: הכל, בכל הטבלאות
  foreach t in array array['agent_comp','agent_manager_cut','revenue_recognition','revenue_month_close','payroll_bonus','staff_hourly_rate'] loop
    execute format('drop policy if exists pf_admin_all on public.%I', t);
    execute format('create policy pf_admin_all on public.%I for all to authenticated using (%s) with check (%s)', t, v_admin, v_admin);
  end loop;

  -- סוכן: קריאה של השורה/השורות שלו בלבד
  execute 'drop policy if exists pf_sales_own_read on public.agent_comp';
  execute format('create policy pf_sales_own_read on public.agent_comp for select to authenticated using (%s and %s)', v_sales, v_mine);

  execute 'drop policy if exists pf_sales_own_read on public.revenue_recognition';
  execute format('create policy pf_sales_own_read on public.revenue_recognition for select to authenticated using (%s and %s)', v_sales, v_mine);

  -- סוכן: רואה אילו חודשים נסגרו + עלות הגרפיקה למודעה (בלי שעות ושכר)
  execute 'drop policy if exists pf_sales_read on public.revenue_month_close';
  execute format('create policy pf_sales_read on public.revenue_month_close for select to authenticated using (%s)', v_sales);
end $mig$;

-- ==================== 3. הרשאות ====================
grant select, insert, update, delete on public.agent_comp, public.agent_manager_cut,
  public.revenue_recognition, public.revenue_month_close, public.payroll_bonus, public.staff_hourly_rate to authenticated;
grant all on public.agent_comp, public.agent_manager_cut, public.revenue_recognition,
  public.revenue_month_close, public.payroll_bonus, public.staff_hourly_rate to service_role;

-- ==================== 4. הגדרות ברירת מחדל ====================
-- רק אם חסרות — לא דורס ערך שכבר הוגדר. המודול נשאר כבוי.
insert into public.settings (key, value)
select v.key, v.value
from (values ('profitability_enabled', '0'), ('graphics_fee_net', '50')) as v(key, value)
where not exists (select 1 from public.settings s where s.key = v.key);
