-- ============================================================
-- מיגרציה: מעקב היסטוריה מלא — Audit (פיצ'ר #11)
-- ------------------------------------------------------------
-- טבלת audit_log + פונקציית טריגר גנרית + טריגרים על טבלאות
-- הליבה: customers, leads, ads, charges, payments, contracts.
-- כל עדכון נרשם פר-שדה (ערך ישן → חדש), כל יצירה/מחיקה נרשמת
-- כרשומה אחת. שם המשתמש = auth.uid() של מבצע הפעולה (פעולות
-- שרת עם service_role נרשמות בלי משתמש).
--
-- ביצועים: נרשמים רק שדות שהשתנו בפועל; שדות רועשים מדולגים.
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ==================== 1. הטבלה ====================
create table if not exists public.audit_log (
  id         bigint generated by default as identity,
  table_name text not null,
  row_id     bigint,
  action     text not null default 'update',
  field      text,
  old_value  text,
  new_value  text,
  user_id    uuid,
  at         timestamptz not null default now()
);

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'audit_log_pkey') then
    alter table public.audit_log add constraint audit_log_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'audit_log_action_check') then
    alter table public.audit_log add constraint audit_log_action_check
      check (action in ('insert','update','delete'));
  end if;
end $mig$;

create index if not exists audit_log_row_idx  on public.audit_log (table_name, row_id, at desc);
create index if not exists audit_log_at_idx   on public.audit_log (at desc);

comment on table public.audit_log is 'מעקב היסטוריה: מי שינה מה ומתי, פר שדה, בטבלאות הליבה';

-- ==================== 2. RLS ====================
-- מנהל רואה הכל; משתמש אחר רואה רק רשומות שהוא עצמו יצר.
-- הכתיבה נעשית ע"י הטריגר (security definer) — לא ישירות מהלקוח.
alter table public.audit_log enable row level security;

do $mig$
begin
  execute 'drop policy if exists audit_log_admin_all on public.audit_log';
  execute $p$
    create policy audit_log_admin_all on public.audit_log
      for select to authenticated
      using (exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role = 'admin'))
  $p$;
  execute 'drop policy if exists audit_log_own on public.audit_log';
  execute $p$
    create policy audit_log_own on public.audit_log
      for select to authenticated
      using (user_id = auth.uid())
  $p$;
end $mig$;

grant select on public.audit_log to authenticated;
grant all on public.audit_log to service_role;

-- ==================== 3. פונקציית הטריגר הגנרית ====================
create or replace function public.audit_track() returns trigger
language plpgsql security definer set search_path = public
as $fn$
declare
  v_old  jsonb;
  v_new  jsonb;
  v_row  bigint;
  k      text;
  -- שדות רועשים / רגישים שלא נרשמים
  skip   constant text[] := array['created_at','updated_at','portal_token','tags'];
begin
  if tg_op = 'INSERT' then
    begin v_row := (to_jsonb(new)->>'id')::bigint; exception when others then v_row := null; end;
    insert into audit_log (table_name, row_id, action, user_id)
    values (tg_table_name, v_row, 'insert', auth.uid());
    return new;
  end if;

  if tg_op = 'DELETE' then
    begin v_row := (to_jsonb(old)->>'id')::bigint; exception when others then v_row := null; end;
    insert into audit_log (table_name, row_id, action, user_id)
    values (tg_table_name, v_row, 'delete', auth.uid());
    return old;
  end if;

  v_old := to_jsonb(old);
  v_new := to_jsonb(new);
  begin v_row := (v_new->>'id')::bigint; exception when others then v_row := null; end;
  for k in select jsonb_object_keys(v_new) loop
    if k = any(skip) then continue; end if;
    if v_old->k is distinct from v_new->k then
      insert into audit_log (table_name, row_id, action, field, old_value, new_value, user_id)
      values (tg_table_name, v_row, 'update', k,
              left(coalesce(v_old->>k, ''), 500),
              left(coalesce(v_new->>k, ''), 500),
              auth.uid());
    end if;
  end loop;
  return new;
end;
$fn$;

-- ==================== 4. טריגרים על טבלאות הליבה ====================
-- שלב ראשון: הליבה בלבד (לפי ספר הבנייה). טבלאות נוספות — בשלב הבא.
do $mig$
declare t text;
begin
  foreach t in array array['customers','leads','ads','charges','payments','contracts'] loop
    if to_regclass('public.' || t) is null then
      raise notice 'טבלה % לא קיימת במופע — מדלג', t;
      continue;
    end if;
    execute format('drop trigger if exists audit_%I on public.%I', t, t);
    execute format($t$
      create trigger audit_%I
        after insert or update or delete on public.%I
        for each row execute function public.audit_track()
    $t$, t, t);
  end loop;
end $mig$;
