-- ============================================================
-- מיגרציה: מנוע התראות גנרי (Alerts Engine) — שלב 1
-- ------------------------------------------------------------
-- זרימה: מקור אירוע → alert_events → מנוע כללים (dedup+throttle)
--        → alerts → alert_deliveries → משלוח לערוצים.
-- שלב 1: ערוץ "מערכת" (inapp) פעיל; מייל/וואטסאפ = stub בלבד.
--
-- מה בקובץ:
--   1. ארבע טבלאות: alert_rules, alert_events, alerts, alert_deliveries
--      + אינדקסים + RLS (מנהל בלבד, לפי דפוס invoice_requests).
--   2. מתגים ב-settings (הכל כבוי כברירת מחדל).
--   3. כלל ברירת מחדל: debt_over_threshold (סף 5000, ערוץ inapp).
--   4. פונקציית סריקה יומית alerts_scan_debts() — יצרן האירועים.
--   5. תזמון יומי דרך pg_cron אם זמין; אם לא — הודעת NOTICE עם החלופה.
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- המנוע מודיע בלבד — אף פעולה כספית לא מתבצעת מכאן.
-- ============================================================

-- ==================== 1. טבלאות ====================

-- ----- alert_rules: הכללים — מתי אירוע הופך להתראה ולאן -----
create table if not exists public.alert_rules (
  id             bigint generated by default as identity,
  event_type     text not null,
  enabled        boolean not null default true,
  condition      jsonb not null default '{}'::jsonb,
  channels       text[] not null default array['inapp'],
  template       text,
  throttle_hours int not null default 24,
  recipients     jsonb not null default '{"roles":["admin"]}'::jsonb,
  created_at     timestamptz not null default now()
);

-- ----- alert_events: כל אירוע שפורסם למנוע (עובד/לא עובד) -----
create table if not exists public.alert_events (
  id           bigint generated by default as identity,
  event_type   text not null,
  payload      jsonb not null default '{}'::jsonb,
  source       text,
  created_at   timestamptz not null default now(),
  processed_at timestamptz
);

-- ----- alerts: ההתראות עצמן (מה שרואים בפעמון) -----
create table if not exists public.alerts (
  id         bigint generated by default as identity,
  rule_id    bigint,
  event_id   bigint,
  title      text not null,
  body       text,
  severity   text not null default 'info',
  dedup_key  text,
  status     text not null default 'new',
  created_at timestamptz not null default now(),
  read_at    timestamptz
);

-- ----- alert_deliveries: רשומת משלוח פר ערוץ -----
create table if not exists public.alert_deliveries (
  id              bigint generated by default as identity,
  alert_id        bigint not null,
  channel         text not null,
  status          text not null default 'queued',
  error           text,
  provider_msg_id text,
  created_at      timestamptz not null default now(),
  sent_at         timestamptz
);

-- ----- אילוצים — בנפרד כדי שהרצה חוזרת לא תיכשל -----
do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'alert_rules_pkey') then
    alter table public.alert_rules add constraint alert_rules_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alert_events_pkey') then
    alter table public.alert_events add constraint alert_events_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alerts_pkey') then
    alter table public.alerts add constraint alerts_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alert_deliveries_pkey') then
    alter table public.alert_deliveries add constraint alert_deliveries_pkey primary key (id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'alerts_status_check') then
    alter table public.alerts add constraint alerts_status_check
      check (status in ('new','read','dismissed'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alerts_severity_check') then
    alter table public.alerts add constraint alerts_severity_check
      check (severity in ('info','warning','critical'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alert_deliveries_status_check') then
    alter table public.alert_deliveries add constraint alert_deliveries_status_check
      check (status in ('queued','sent','failed'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alert_deliveries_channel_check') then
    alter table public.alert_deliveries add constraint alert_deliveries_channel_check
      check (channel in ('inapp','email','whatsapp'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'alerts_rule_id_fkey') then
    alter table public.alerts add constraint alerts_rule_id_fkey
      foreign key (rule_id) references public.alert_rules(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alerts_event_id_fkey') then
    alter table public.alerts add constraint alerts_event_id_fkey
      foreign key (event_id) references public.alert_events(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'alert_deliveries_alert_id_fkey') then
    alter table public.alert_deliveries add constraint alert_deliveries_alert_id_fkey
      foreign key (alert_id) references public.alerts(id) on delete cascade;
  end if;
end $mig$;

-- ----- אינדקסים -----
create index if not exists alert_events_unprocessed_idx
  on public.alert_events (created_at) where processed_at is null;
create index if not exists alerts_status_idx     on public.alerts (status);
create index if not exists alerts_created_idx    on public.alerts (created_at desc);
create index if not exists alerts_dedup_time_idx on public.alerts (dedup_key, created_at desc);
-- מניעת כפילות ברמת DB: לא תיתכן יותר מהתראה *פתוחה* אחת לאותו dedup_key.
-- (חלון הזמן של throttle_hours נאכף במנוע — אינדקס ייחודי לא יכול לבטא חלון זמן.)
create unique index if not exists alerts_dedup_open_uq
  on public.alerts (dedup_key) where status = 'new' and dedup_key is not null;
create index if not exists alert_deliveries_queued_idx
  on public.alert_deliveries (created_at) where status = 'queued';

comment on table public.alert_rules      is 'מנוע התראות: כללים — מתי אירוע הופך להתראה, לאילו ערוצים ולמי';
comment on table public.alert_events     is 'מנוע התראות: אירועים שפורסמו ע"י חלקי המערכת (יצרנים)';
comment on table public.alerts           is 'מנוע התראות: ההתראות שנוצרו (מוצגות בפעמון ההתראות)';
comment on table public.alert_deliveries is 'מנוע התראות: רשומת משלוח לכל ערוץ (inapp/email/whatsapp)';

-- ==================== RLS — מנהל בלבד ====================
-- המנוע (Edge Function) כותב עם service_role שעוקף RLS;
-- בדפדפן רק מנהל פעיל רואה ומעדכן. (בשלב 1 הנמענים = מנהל בלבד.)

alter table public.alert_rules      enable row level security;
alter table public.alert_events     enable row level security;
alter table public.alerts           enable row level security;
alter table public.alert_deliveries enable row level security;

do $mig$
declare t text;
begin
  foreach t in array array['alert_rules','alert_events','alerts','alert_deliveries'] loop
    execute format('drop policy if exists %I_admin_all on public.%I', t, t);
    execute format($p$
      create policy %I_admin_all on public.%I
        for all to authenticated
        using (exists (select 1 from public.profiles p
                       where p.id = auth.uid() and p.active and p.role = 'admin'))
        with check (exists (select 1 from public.profiles p
                            where p.id = auth.uid() and p.active and p.role = 'admin'))
    $p$, t, t);
  end loop;
end $mig$;

grant all on public.alert_rules, public.alert_events, public.alerts, public.alert_deliveries
  to anon, authenticated, service_role;

-- ==================== 2. מתגים ב-settings ====================
-- הכל כבוי כברירת מחדל — הפיצ'ר לא פעיל באף מופע עד הדלקה ידנית.
insert into public.settings (key, value) values ('alerts_enabled', '0')
  on conflict (key) do nothing;
insert into public.settings (key, value) values ('alerts_email_enabled', '0')
  on conflict (key) do nothing;
insert into public.settings (key, value) values ('alerts_whatsapp_enabled', '0')
  on conflict (key) do nothing;

-- ==================== 3. כלל ברירת מחדל ====================
insert into public.alert_rules (event_type, enabled, condition, channels, template, throttle_hours, recipients)
select 'debt_over_threshold', true, '{"threshold": 5000}'::jsonb, array['inapp'],
       'ללקוח {customer_name} חוב פתוח של {balance} — מעל הסף ({threshold})',
       24, '{"roles":["admin"]}'::jsonb
where not exists (select 1 from public.alert_rules where event_type = 'debt_over_threshold');

-- ==================== 4. הסורק היומי — יצרן האירוע ====================
-- מחשב יתרה פתוחה לכל לקוח (חיובים פתוחים פחות תשלומים — אותו חישוב
-- כמו customerOpenBalance בקוד הלקוח) וכותב alert_events ללקוחות מעל
-- הסף הנמוך ביותר מבין הכללים הפעילים. לא נוגע בכסף — רק כותב אירועים.
create or replace function public.alerts_scan_debts() returns integer
language plpgsql security definer set search_path = public
as $fn$
declare
  v_threshold numeric;
  v_count     integer := 0;
begin
  -- מתג ראשי כבוי → לא עושים כלום
  if coalesce((select value from settings where key = 'alerts_enabled'), '0') <> '1' then
    return 0;
  end if;

  select min((condition->>'threshold')::numeric) into v_threshold
  from alert_rules
  where event_type = 'debt_over_threshold' and enabled
    and (condition->>'threshold') ~ '^[0-9]+(\.[0-9]+)?$';
  if v_threshold is null then
    return 0;
  end if;

  with open_charges as (
    select id, customer_id, amount::numeric as amount
    from charges
    where status in ('pending','invoiced','partial','overdue')
  ),
  pays as (
    select charge_id, sum(amount::numeric) as paid
    from payments
    where charge_id in (select id from open_charges)
    group by charge_id
  ),
  bal as (
    select oc.customer_id,
           sum(greatest(oc.amount - coalesce(p.paid, 0), 0)) as balance
    from open_charges oc
    left join pays p on p.charge_id = oc.id
    group by oc.customer_id
  ),
  ins as (
    insert into alert_events (event_type, payload, source)
    select 'debt_over_threshold',
           jsonb_build_object(
             'customer_id',   b.customer_id,
             'customer_name', coalesce(c.name, 'לקוח #' || b.customer_id),
             'balance',       round(b.balance, 2)
           ),
           'daily_scan'
    from bal b
    join customers c on c.id = b.customer_id
    where b.balance >= v_threshold
      -- לא לערום אירוע חדש כשיש כבר אירוע זהה שממתין לעיבוד
      and not exists (
        select 1 from alert_events e
        where e.event_type = 'debt_over_threshold'
          and e.processed_at is null
          and (e.payload->>'customer_id')::bigint = b.customer_id
      )
    returning 1
  )
  select count(*) into v_count from ins;

  return v_count;
end;
$fn$;

revoke all on function public.alerts_scan_debts() from public, anon, authenticated;
grant execute on function public.alerts_scan_debts() to service_role;

-- ==================== 5. תזמון יומי ====================
-- מנסה pg_cron (זמין בפרויקטי Supabase; נבדק כאן בזמן ההרצה בכל מופע).
-- הצלחה → סריקה יומית ב-03:00 UTC (05:00/06:00 בישראל, חורף/קיץ).
-- כישלון → NOTICE עם החלופה: תזמון alerts-engine דרך
-- Dashboard → Integrations → Cron (Scheduled Function), פעם ביום.
do $mig$
begin
  begin
    create extension if not exists pg_cron;
  exception when others then
    raise notice 'pg_cron לא זמין במופע הזה (%). חלופה: לתזמן את ה-Edge Function ‏alerts-engine פעם ביום דרך Dashboard → Integrations → Cron.', sqlerrm;
    return;
  end;

  begin
    perform cron.unschedule('alerts-daily-debt-scan');
  exception when others then
    null; -- הג'וב עוד לא קיים — זה בסדר
  end;

  perform cron.schedule('alerts-daily-debt-scan', '0 3 * * *',
                        'select public.alerts_scan_debts();');
  raise notice 'תוזמן ג''וב יומי: alerts-daily-debt-scan (03:00 UTC).';
exception when others then
  raise notice 'תזמון pg_cron נכשל (%). חלופה: לתזמן את alerts-engine דרך Dashboard → Integrations → Cron.', sqlerrm;
end $mig$;
