-- ============================================================
-- מיגרציה: עוזר AI אחוד (שלב 1 — קריאה בלבד)
-- ------------------------------------------------------------
-- 1. טבלת assistant_audit — יומן כל קריאת כלי של העוזר:
--    מי (user_id + role), איזה כלי, עם אילו פרמטרים, מתי, וסיכום
--    התוצאה (מספר שורות / שגיאה — בלי תוכן הרשומות, בלי PII מלא).
--    phase: requested (המודל ביקש) · result (הכלי רץ אצל המשתמש וחזר)
--           · confirm / cancel (שלב 2 — אישור/ביטול כתיבה בממשק).
--    הכתיבה נעשית תחת ה-JWT של המשתמש עצמו (לא service_role):
--    כל משתמש מוסיף רק שורות של עצמו; אין update/delete לאף אחד
--    (יומן append-only). מנהל רואה הכל, משתמש רואה רק את שלו.
-- 2. מתגים בהגדרות (נזרעים רק אם חסרים):
--    assistant_enabled = '0'          — הפיצ'ר כבוי עד הדלקה ידנית
--    assistant_roles   = 'admin,sales' — אילו תפקידים מקבלים את העוזר
-- דורש: ANTHROPIC_API_KEY ב-Supabase → Edge Functions → Secrets
-- (אותו סוד של parse-invoice-text / manager-agent), ופריסת הפונקציה assistant.
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ==================== 1. יומן הביקורת ====================
create table if not exists public.assistant_audit (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  user_id        uuid not null default auth.uid(),
  role           text,
  tool           text not null,
  phase          text not null default 'requested'
                   check (phase in ('requested', 'result', 'confirm', 'cancel', 'denied')),
  tool_use_id    text,
  args           jsonb,
  result_summary jsonb
);
create index if not exists assistant_audit_user_idx on public.assistant_audit (user_id, created_at desc);
create index if not exists assistant_audit_created_idx on public.assistant_audit (created_at desc);
comment on table public.assistant_audit is
  'יומן העוזר האחוד: כל קריאת כלי (מי, מה, פרמטרים, סיכום תוצאה). append-only, נכתב תחת ה-JWT של המשתמש.';

alter table public.assistant_audit enable row level security;

drop policy if exists assistant_audit_insert_own on public.assistant_audit;
create policy assistant_audit_insert_own on public.assistant_audit
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists assistant_audit_select on public.assistant_audit;
create policy assistant_audit_select on public.assistant_audit
  for select to authenticated
  using (user_id = auth.uid() or public.emu_is_admin());

-- בכוונה אין מדיניות update/delete — היומן לא ניתן לעריכה או למחיקה מהאפליקציה.
revoke update, delete on public.assistant_audit from authenticated, anon;
grant select, insert on public.assistant_audit to authenticated;
grant all on public.assistant_audit to service_role;

-- ==================== 2. הגדרות ====================
insert into public.settings (key, value)
  select 'assistant_enabled', '0'
  where not exists (select 1 from public.settings where key = 'assistant_enabled');
insert into public.settings (key, value)
  select 'assistant_roles', 'admin,sales'
  where not exists (select 1 from public.settings where key = 'assistant_roles');
