-- ============================================================
-- מיגרציה: סוכן המקומון (שלב א') — צ'אט סוכן למנהל
-- ------------------------------------------------------------
-- 1. טבלת agent_chats — שמירת שיחות הסוכן (תמליל מלא כ-JSONB)
--    להמשכיות ולביקורת. ההפקות הכספיות עצמן ממשיכות להירשם
--    ב-invoice_requests כמו היום — הטבלה הזו היא רק השיחה.
-- 2. מתג בהגדרות: manager_agent_enabled ('0' כברירת מחדל).
-- דורש: ANTHROPIC_API_KEY מוגדר ב-Supabase → Edge Functions → Secrets
-- (אותו סוד של צ'אט החשבוניות), ופריסת הפונקציה manager-agent.
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- עד שהמיגרציה רצה — הפיצ'ר רדום (המתג לא קיים = כבוי).
-- ============================================================

-- ==================== 1. טבלת השיחות ====================
create table if not exists public.agent_chats (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid,
  title text,
  messages jsonb not null default '[]'::jsonb
);

-- אילוצים — בנפרד כדי שהרצה חוזרת לא תיכשל
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'agent_chats_pkey') then
    alter table public.agent_chats add constraint agent_chats_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'agent_chats_user_id_fkey') then
    alter table public.agent_chats add constraint agent_chats_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete set null;
  end if;
end $$;

create index if not exists agent_chats_user_idx    on public.agent_chats (user_id, updated_at desc);
create index if not exists agent_chats_updated_idx on public.agent_chats (updated_at desc);

comment on table public.agent_chats is
  'שיחות סוכן המקומון: תמליל מלא (כולל קריאות כלים) לכל שיחה, להמשכיות וביקורת';

-- RLS: מנהל בלבד, ורק על השיחות של עצמו
alter table public.agent_chats enable row level security;

drop policy if exists agent_chats_select on public.agent_chats;
create policy agent_chats_select on public.agent_chats
  for select to authenticated
  using (user_id = auth.uid()
         and exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role = 'admin'));

drop policy if exists agent_chats_insert on public.agent_chats;
create policy agent_chats_insert on public.agent_chats
  for insert to authenticated
  with check (user_id = auth.uid()
              and exists (select 1 from public.profiles p
                          where p.id = auth.uid() and p.active and p.role = 'admin'));

drop policy if exists agent_chats_update on public.agent_chats;
create policy agent_chats_update on public.agent_chats
  for update to authenticated
  using (user_id = auth.uid()
         and exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role = 'admin'))
  with check (user_id = auth.uid()
              and exists (select 1 from public.profiles p
                          where p.id = auth.uid() and p.active and p.role = 'admin'));

grant all on public.agent_chats to anon, authenticated, service_role;

-- ==================== 2. מתג בהגדרות ====================
insert into public.settings (key, value) values ('manager_agent_enabled', '0')
  on conflict (key) do nothing;
