-- ============================================================
-- מיגרציה: טבלת customer_tasks — משימות ותזכורות ללקוח
-- ------------------------------------------------------------
-- הקוד (js/customer-tasks.js) קיים מזמן ומזהה בעדינות שהטבלה
-- חסרה ("התכונה תופעל לאחר עדכון מסד הנתונים") — המיגרציה הזו
-- היא שמפעילה את הפיצ'ר בפועל.
-- כוללת גם את פוליסת ה-RESTRICTIVE לסוכנים (zz_sales_customer_tasks)
-- מהמיגרציה 2026-08-24_sales_least_privilege_rls.sql — שם היא דולגה
-- כי הטבלה עוד לא הייתה קיימת.
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ==================== 1. הטבלה ====================
create table if not exists public.customer_tasks (
  id          bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  title       text not null,
  due_date    date,
  done        boolean not null default false,
  done_at     timestamptz,
  assigned_to uuid,
  created_by  uuid,
  created_at  timestamptz not null default now()
);

create index if not exists customer_tasks_cust_idx on public.customer_tasks (customer_id, done);
create index if not exists customer_tasks_due_idx  on public.customer_tasks (done, due_date);

comment on table public.customer_tasks is 'משימות ותזכורות פר לקוח (כרטיס לקוח + וידג''ט דף הבית)';

-- ==================== 2. RLS ====================
-- בסיס: אנשי צוות פעילים בתפקיד admin/sales (כמו ה-UI).
alter table public.customer_tasks enable row level security;

do $mig$
begin
  execute 'drop policy if exists customer_tasks_staff on public.customer_tasks';
  execute $p$
    create policy customer_tasks_staff on public.customer_tasks
      for all to authenticated
      using (exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role in ('admin','sales')))
      with check (exists (select 1 from public.profiles p
                          where p.id = auth.uid() and p.active and p.role in ('admin','sales')))
  $p$;
end $mig$;

-- פוליסת ה-least-privilege לסוכנים (העתק מ-2026-08-24, מותנית בקיום
-- פונקציות העזר — במופע שטרם הריץ את מיגרציית ה-RLS היא תדולג).
do $do$ begin
  if to_regprocedure('public.emu_is_admin()') is not null
     and to_regprocedure('public.my_role()') is not null
     and to_regprocedure('public.my_agent_id()') is not null then
    execute $p$drop policy if exists zz_sales_customer_tasks on public.customer_tasks$p$;
    execute $p$create policy zz_sales_customer_tasks on public.customer_tasks as restrictive for all to public using ( public.emu_is_admin() or public.my_role() <> 'sales' or assigned_to = auth.uid() or customer_id in (select id from public.customers where agent_id = public.my_agent_id()) ) with check ( public.emu_is_admin() or public.my_role() <> 'sales' or assigned_to = auth.uid() or customer_id in (select id from public.customers where agent_id = public.my_agent_id()) )$p$;
  end if;
end $do$;

-- ==================== 3. הרשאות ====================
grant select, insert, update, delete on public.customer_tasks to authenticated;
grant all on public.customer_tasks to service_role;
