-- ============================================================
-- מיגרציה: ברכת "בוקר טוב" יומית לכל הצוות — שלב 1 (inapp)
-- ------------------------------------------------------------
-- מרחיבה את מנוע ההתראות (חובה להריץ קודם את 2026-08-24_alerts_engine.sql
-- ואת 2026-08-30_alerts_engine_v2.sql). הודעה מתוזמנת ראשונה במנוע:
-- מופעלת לפי שעה (לא לפי נתונים) ומיועדת לכל הצוות (לא רק מנהל).
--
-- מה בקובץ:
--   1. עמודת alerts.user_id — התראה ממוענת למשתמש מסוים (null = כמו
--      היום: התראת מנהל). RLS מעודכן: כל משתמש פעיל רואה ומעדכן את
--      ההתראות *שלו*; התראות ללא נמען נשארות מנהל בלבד.
--   2. טבלת morning_messages — מאגר הודעות קטן וניתן לעריכה + זריעה.
--      הודעה יכולה להכיל {city} — מוחלף בשם העיר של המופע
--      (settings.paper_city, נערך במסך ההגדרות ליד שם העיתון).
--   3. מתגים: settings.morning_greeting_enabled (ברירת מחדל '0' — כבוי)
--      ו-settings.paper_city (ריק — עד שממלאים בהגדרות).
--   4. סורק alerts_scan_morning(): פעם בבוקר (לפי תאריך ישראל) יוצר
--      אירוע good_morning + התראת inapp לכל משתמש פעיל, עם רוטציית
--      הודעה לפי יום-בשנה. dedup: good_morning:<user>:<date>.
--   5. עדכון alerts_scan_all() לכלול את הסורק — כך ריצת הכניסה של
--      המנוע (fallback) יוצרת את הברכה גם בלי pg_cron.
--   6. RPC ‏alerts_morning_test() — "שלח בדיקה" למנהל בלבד.
--   7. ג'וב pg_cron יומי ב-05:00 UTC. שים לב: 05:00 UTC = 08:00 בקיץ
--      (IDT) אבל 07:00 בחורף (IST) — cron רץ ב-UTC ואינו מכיר שעון קיץ.
--      נשאר פשוט בכוונה: ג'וב אחד, והפונקציה עצמה שומרת "פעם ביום,
--      לא לפני 05:00 שעון ישראל".
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- המנוע מודיע בלבד — אף פעולה כספית לא מתבצעת מכאן.
-- ============================================================

-- ==================== 1. alerts.user_id + RLS ====================

alter table public.alerts add column if not exists user_id uuid;

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'alerts_user_id_fkey') then
    alter table public.alerts add constraint alerts_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade;
  end if;
end $mig$;

create index if not exists alerts_user_status_idx on public.alerts (user_id, status);

-- המדיניות הישנה (מנהל רואה הכל) מוחלפת בשלוש ממוקדות:
--   - מנהל: שליטה מלאה בהתראות ללא נמען (ההתנהגות הקיימת);
--   - כל משתמש פעיל: רואה ומעדכן (נקרא/הוסר) את ההתראות הממוענות אליו.
-- המנוע עצמו כותב עם service_role — עוקף RLS, לא מושפע.
drop policy if exists alerts_admin_all on public.alerts;
drop policy if exists alerts_admin_broadcast on public.alerts;
create policy alerts_admin_broadcast on public.alerts
  for all to authenticated
  using (user_id is null and exists (select 1 from public.profiles p
         where p.id = auth.uid() and p.active and p.role = 'admin'))
  with check (user_id is null and exists (select 1 from public.profiles p
              where p.id = auth.uid() and p.active and p.role = 'admin'));

drop policy if exists alerts_own_select on public.alerts;
create policy alerts_own_select on public.alerts
  for select to authenticated
  using (user_id = auth.uid() and exists (select 1 from public.profiles p
         where p.id = auth.uid() and p.active));

drop policy if exists alerts_own_update on public.alerts;
create policy alerts_own_update on public.alerts
  for update to authenticated
  using (user_id = auth.uid() and exists (select 1 from public.profiles p
         where p.id = auth.uid() and p.active))
  with check (user_id = auth.uid());

comment on column public.alerts.user_id
  is 'נמען ההתראה. null = התראת מנהל (ברירת המחדל ההיסטורית); אחרת — רק המשתמש הזה רואה אותה.';

-- ==================== 2. מאגר הודעות הבוקר ====================

create table if not exists public.morning_messages (
  id         bigint generated by default as identity,
  text       text not null,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'morning_messages_pkey') then
    alter table public.morning_messages add constraint morning_messages_pkey primary key (id);
  end if;
end $mig$;

alter table public.morning_messages enable row level security;

drop policy if exists morning_messages_admin_all on public.morning_messages;
create policy morning_messages_admin_all on public.morning_messages
  for all to authenticated
  using (exists (select 1 from public.profiles p
                 where p.id = auth.uid() and p.active and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p
                      where p.id = auth.uid() and p.active and p.role = 'admin'));

grant all on public.morning_messages to anon, authenticated, service_role;

comment on table public.morning_messages
  is 'ברכת בוקר יומית: מאגר ההודעות (רוטציה לפי יום-בשנה). עריכה — מנהל, במסך ההגדרות.';

-- זריעה — רק אם המאגר ריק (לא דורס עריכות של המנהל)
insert into public.morning_messages (text)
select v.msg from (values
  ('בוקר טוב 🌅 יום חדש, הזדמנויות חדשות. בוא נפתח אותו בשיחה אחת טובה.'),
  ('בוקר טוב! כל "לא" מקרב אותך ל"כן" הבא. קדימה, אנחנו איתך.'),
  ('בוקר טוב ☕ שלוש שיחות לפני 10:00 — וכבר פתחת את היום בניצחון.'),
  ('בוקר טוב! העסקים ב{city} מחכים שתגיע אליהם. אתה הקול שלהם בכל בית.'),
  ('בוקר טוב 💪 היום לא מתחילים חזק — היום מתחילים ומתחזקים תוך כדי. יאללה.'),
  ('בוקר טוב! לקוח מרוצה מביא עוד לקוח. תעשה היום אחד מאושר.'),
  ('בוקר טוב 🎯 מטרה אחת ברורה להיום עדיפה על עשר משאלות. מה שלך?'),
  ('בוקר טוב! אתה חלק מהעיתון הכי גדול ב{city}. תמכור בגאווה.')
) as v(msg)
where not exists (select 1 from public.morning_messages);

-- ==================== 3. מתגים ====================
-- כבוי כברירת מחדל — חיים מדליק מההגדרות כשמוכן. דורש גם את המתג
-- הראשי alerts_enabled='1' (בלעדיו אין פעמון בכלל).
insert into public.settings (key, value) values ('morning_greeting_enabled', '0')
  on conflict (key) do nothing;
-- שם העיר/היישוב של המופע — משתנה פר עסק, נערך במסך ההגדרות (ליד שם
-- העיתון). מציב את {city} בהודעות הבוקר; ריק → "עיר שלנו".
insert into public.settings (key, value) values ('paper_city', '')
  on conflict (key) do nothing;

-- ==================== 4. הסורק — יצרן הברכה ====================
-- שונה מהסורקים האחרים: מופעל לפי זמן, והוא גם *מעבד* את האירוע בעצמו
-- (התראה פר משתמש פעיל + רשומת משלוח inapp), כי המנוע הגנרי ממען לפי
-- כללים למנהל בלבד. עדיין עובר דרך אותן טבלאות: event → alerts →
-- deliveries, ואותו דפוס dedup_key. פעם אחת בבוקר לכל היותר.
create or replace function public.alerts_scan_morning() returns integer
language plpgsql security definer set search_path = public
as $fn$
declare
  v_now_il   timestamp;  -- שעון קיר ישראל (Postgres מטפל בשעון קיץ)
  v_today    date;
  v_msg      text;
  v_city     text;
  v_active   integer;
  v_event_id bigint;
  v_count    integer := 0;
begin
  if coalesce((select value from settings where key = 'alerts_enabled'), '0') <> '1'
     or coalesce((select value from settings where key = 'morning_greeting_enabled'), '0') <> '1' then
    return 0;
  end if;

  v_now_il := now() at time zone 'Asia/Jerusalem';
  v_today  := v_now_il::date;
  -- לא מברכים "בוקר טוב" באמצע הלילה (ריצת כניסה של מנהל מוקדם/מאוחר)
  if v_now_il::time < time '05:00' then
    return 0;
  end if;

  -- פעם אחת בבוקר: כבר נוצר אירוע good_morning היום (לפי תאריך ישראל)?
  if exists (
    select 1 from alert_events e
    where e.event_type = 'good_morning'
      and (e.created_at at time zone 'Asia/Jerusalem')::date = v_today
  ) then
    return 0;
  end if;

  -- רוטציה: יום-בשנה מודולו מספר ההודעות הפעילות
  select count(*) into v_active from morning_messages where active;
  if v_active = 0 then
    return 0;
  end if;
  select t.text into v_msg
  from (select m.text, row_number() over (order by m.id) - 1 as rn
        from morning_messages m where m.active) t
  where t.rn = extract(doy from v_today)::int % v_active;

  -- {city} → שם העיר של המופע (משתנה פר עסק, מוגדר בהגדרות)
  v_city := coalesce(nullif(btrim((select value from settings where key = 'paper_city')), ''), 'עיר שלנו');
  v_msg  := replace(v_msg, '{city}', v_city);

  insert into alert_events (event_type, payload, source)
  values ('good_morning',
          jsonb_build_object('message', v_msg, 'date', v_today),
          'morning_schedule')
  returning id into v_event_id;

  -- התראה לכל משתמש פעיל בצוות (לא pending, לא ועדה — אין להם פעמון).
  -- dedup: לכל היותר ברכה אחת למשתמש ליום, גם מול ריצות מקבילות.
  with ins as (
    insert into alerts (event_id, title, severity, dedup_key, status, user_id)
    select v_event_id, v_msg, 'info',
           'good_morning:' || p.id || ':' || v_today, 'new', p.id
    from profiles p
    where p.active and p.role not in ('pending', 'committee')
      and not exists (
        select 1 from alerts a
        where a.dedup_key = 'good_morning:' || p.id || ':' || v_today
      )
    returning id
  ), dv as (
    insert into alert_deliveries (alert_id, channel, status, sent_at)
    select ins.id, 'inapp', 'sent', now() from ins
    returning 1
  )
  select count(*) into v_count from ins;

  update alert_events set processed_at = now() where id = v_event_id;

  return v_count;
end;
$fn$;

revoke all on function public.alerts_scan_morning() from public, anon, authenticated;
grant execute on function public.alerts_scan_morning() to service_role;

comment on function public.alerts_scan_morning()
  is 'ברכת בוקר יומית: פעם בבוקר (שעון ישראל) — התראת inapp לכל משתמש פעיל, הודעה ברוטציה.';

-- ==================== 5. עדכון העוטף — fallback בכניסה ====================
-- ריצת המנוע בכניסת מנהל קוראת ל-alerts_scan_all — כך הברכה נוצרת
-- גם במופע בלי pg_cron (באיחור, בכניסה הראשונה של הבוקר).
create or replace function public.alerts_scan_all() returns integer
language plpgsql security definer set search_path = public
as $fn$
begin
  return coalesce(public.alerts_scan_debts(), 0)
       + coalesce(public.alerts_scan_issue_deadlines(), 0)
       + coalesce(public.alerts_scan_morning(), 0);
end;
$fn$;

revoke all on function public.alerts_scan_all() from public, anon, authenticated;
grant execute on function public.alerts_scan_all() to service_role;

-- ==================== 6. "שלח בדיקה" — מנהל בלבד ====================
-- יוצר את ברכת היום רק למנהל המבקש, בלי dedup (אפשר לבדוק שוב ושוב)
-- ובלי תלות במתגים — כדי שחיים יוכל לראות איך זה נראה לפני ההדלקה.
create or replace function public.alerts_morning_test() returns text
language plpgsql security definer set search_path = public
as $fn$
declare
  v_uid    uuid := auth.uid();
  v_msg    text;
  v_city   text;
  v_active integer;
  v_id     bigint;
begin
  if not exists (select 1 from profiles p
                 where p.id = v_uid and p.active and p.role = 'admin') then
    raise exception 'not allowed';
  end if;

  select count(*) into v_active from morning_messages where active;
  if v_active = 0 then
    raise exception 'אין הודעות פעילות במאגר';
  end if;
  select t.text into v_msg
  from (select m.text, row_number() over (order by m.id) - 1 as rn
        from morning_messages m where m.active) t
  where t.rn = extract(doy from (now() at time zone 'Asia/Jerusalem')::date)::int % v_active;

  v_city := coalesce(nullif(btrim((select value from settings where key = 'paper_city')), ''), 'עיר שלנו');
  v_msg  := replace(v_msg, '{city}', v_city);

  insert into alerts (title, body, severity, status, user_id)
  values (v_msg, '(בדיקה — כך תיראה ברכת הבוקר)', 'info', 'new', v_uid)
  returning id into v_id;
  insert into alert_deliveries (alert_id, channel, status, sent_at)
  values (v_id, 'inapp', 'sent', now());

  return v_msg;
end;
$fn$;

revoke all on function public.alerts_morning_test() from public, anon;
grant execute on function public.alerts_morning_test() to authenticated, service_role;

comment on function public.alerts_morning_test()
  is 'ברכת בוקר: תצוגה מקדימה למנהל המבקש בלבד. עוקף מתגים ו-dedup בכוונה.';

-- ==================== 7. תזמון יומי ====================
-- ג'וב נפרד מ-alerts-daily-scan (שרץ ב-03:00 UTC — לפני 05:00 ישראל
-- בחורף, הברכה הייתה נחסמת). 05:00 UTC = 08:00 קיץ / 07:00 חורף.
do $mig$
begin
  begin
    create extension if not exists pg_cron;
  exception when others then
    raise notice 'pg_cron לא זמין במופע הזה (%). חלופה: לתזמן את ה-Edge Function ‏alerts-engine פעם ביום דרך Dashboard → Integrations → Cron.', sqlerrm;
    return;
  end;

  begin
    perform cron.unschedule('alerts-morning-greeting');
  exception when others then
    null; -- הג'וב עוד לא קיים — זה בסדר
  end;

  perform cron.schedule('alerts-morning-greeting', '0 5 * * *',
                        'select public.alerts_scan_morning();');
  raise notice 'תוזמן ג''וב יומי: alerts-morning-greeting (05:00 UTC ≈ 08:00 ישראל).';
exception when others then
  raise notice 'תזמון pg_cron נכשל (%). חלופה: לתזמן את alerts-engine דרך Dashboard → Integrations → Cron.', sqlerrm;
end $mig$;
