-- ============================================================
-- מיגרציה: מודעות מערכת קבועות (תורנויות, זמנים, טורים קבועים)
-- ------------------------------------------------------------
-- רשימת מודעות מערכת שנכנסות אוטומטית לכל גיליון פתוח:
--   סטטית (static)    — אותו קובץ בכל גיליון, נכנסת מאושרת.
--   מתעדכנת (updating) — צריך קובץ חדש כל גיליון; נכנסת כ"ממתינה"
--                        ומופיעה בבאנר תזכורת בעמוד הגיליונות.
-- ההזרעה נעשית בצד הלקוח (issues.js) בכניסה לעמוד הגיליונות —
-- אין שום פעולה כספית (מחיר 0, is_system).
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- ============================================================

-- ==================== 1. טבלת המודעות הקבועות ====================
create table if not exists public.recurring_ads (
  id            bigint generated by default as identity primary key,
  title         text not null,
  mode          text not null default 'static',   -- static | updating
  price_item_id bigint,                           -- גודל מהמחירון (אופציונלי)
  page_number   int,                              -- עמוד קבוע (אופציונלי)
  notes         text,
  storage_path  text,                             -- הקובץ (בבאקט ad-files, לסוג static)
  file_name     text,
  active        boolean not null default true,
  sort          int not null default 0,
  created_at    timestamptz not null default now()
);

comment on table public.recurring_ads
  is 'מודעות מערכת קבועות — נזרעות אוטומטית לכל גיליון פתוח (issues.js)';
comment on column public.recurring_ads.mode
  is 'static = אותו קובץ כל גיליון · updating = קובץ חדש כל גיליון + תזכורת';

-- ==================== 2. קישור המודעה שנוצרה למקור ====================
alter table public.ads
  add column if not exists recurring_id bigint;

comment on column public.ads.recurring_id
  is 'מזהה המודעה הקבועה (recurring_ads) שממנה נוצרה מודעה זו';

create index if not exists ads_recurring_idx
  on public.ads (recurring_id, issue_id) where recurring_id is not null;

-- ==================== 3. הרשאות (RLS) ====================
alter table public.recurring_ads enable row level security;

drop policy if exists recurring_ads_staff on public.recurring_ads;
create policy recurring_ads_staff on public.recurring_ads
  for all to authenticated
  using (my_role() = any (array['admin','editor']))
  with check (my_role() = any (array['admin','editor']));
