-- ============================================================
-- מיגרציה: לוג תזכורות חוב (debt_reminders) + מתג וואטסאפ למופע
-- ------------------------------------------------------------
-- פיצ'ר #1 — תזכורות חוב בוואטסאפ. שלב א: כפתור ידני בכרטיס
-- הלקוח שפותח wa.me עם הודעה מנוסחת, ורושם כאן שורת לוג.
-- שלב ב (עתידי, דרך מנוע ההתראות): שליחה אוטומטית בערוץ API.
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ את כל הקובץ,
-- בכל מופע בנפרד. בטוח להרצה חוזרת (idempotent).
-- תזכורת בלבד — אין כאן שום חיוב או פעולה כספית.
-- ============================================================

-- ==================== 1. טבלת הלוג ====================
create table if not exists public.debt_reminders (
  id          bigint generated by default as identity,
  customer_id bigint not null,
  amount      numeric not null default 0,
  channel     text not null default 'whatsapp',
  message     text,
  status      text not null default 'opened',
  created_by  uuid,
  created_at  timestamptz not null default now()
);

do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'debt_reminders_pkey') then
    alter table public.debt_reminders add constraint debt_reminders_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'debt_reminders_customer_id_fkey') then
    alter table public.debt_reminders add constraint debt_reminders_customer_id_fkey
      foreign key (customer_id) references public.customers(id) on delete cascade;
  end if;
  -- opened = נפתח חלון wa.me (שליחה ידנית); sent/failed שמורים לערוץ API עתידי
  if not exists (select 1 from pg_constraint where conname = 'debt_reminders_status_check') then
    alter table public.debt_reminders add constraint debt_reminders_status_check
      check (status in ('opened','sent','failed'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'debt_reminders_channel_check') then
    alter table public.debt_reminders add constraint debt_reminders_channel_check
      check (channel in ('whatsapp','email'));
  end if;
end $mig$;

create index if not exists debt_reminders_customer_idx
  on public.debt_reminders (customer_id, created_at desc);

comment on table public.debt_reminders is 'לוג תזכורות חוב שנשלחו ללקוחות (מי, מתי, סכום, ערוץ)';

-- ==================== 2. RLS ====================
-- מנהל: הכל. סוכן מכירות פעיל: רושם ורואה את התזכורות שהוא עצמו שלח.
alter table public.debt_reminders enable row level security;

do $mig$
begin
  execute 'drop policy if exists debt_reminders_admin_all on public.debt_reminders';
  execute $p$
    create policy debt_reminders_admin_all on public.debt_reminders
      for all to authenticated
      using (exists (select 1 from public.profiles p
                     where p.id = auth.uid() and p.active and p.role = 'admin'))
      with check (exists (select 1 from public.profiles p
                          where p.id = auth.uid() and p.active and p.role = 'admin'))
  $p$;

  execute 'drop policy if exists debt_reminders_sales_own on public.debt_reminders';
  execute $p$
    create policy debt_reminders_sales_own on public.debt_reminders
      for all to authenticated
      using (created_by = auth.uid()
             and exists (select 1 from public.profiles p
                         where p.id = auth.uid() and p.active and p.role = 'sales'))
      with check (created_by = auth.uid()
                  and exists (select 1 from public.profiles p
                              where p.id = auth.uid() and p.active and p.role = 'sales'))
  $p$;
end $mig$;

grant all on public.debt_reminders to anon, authenticated, service_role;

-- ==================== 3. מתג פר-מופע ====================
-- כבוי כברירת מחדל — הכפתור לא מוצג עד הדלקה ידנית בהגדרות.
insert into public.settings (key, value) values ('whatsapp_enabled', '0')
  on conflict (key) do nothing;
